In [1]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.datasets import fetch_california_housing
import pandas as pd
import numpy as np

In [2]:
data = fetch_california_housing()

In [3]:
X = data["data"]

In [4]:
col_names = data["feature_names"]

In [5]:
y = data["target"]

In [6]:
df = pd.DataFrame(X, columns=col_names)

In [7]:
df["MedInc_Sqrt"] = df.MedInc.apply(np.sqrt)

In [8]:
df.corr()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedInc_Sqrt
MedInc,1.000000,-0.119034,0.326895,-0.062040,0.004834,0.018766,-0.079809,-0.015176,0.984329
HouseAge,-0.119034,1.000000,-0.153277,-0.077747,-0.296244,0.013191,0.011173,-0.108197,-0.132797
AveRooms,0.326895,-0.153277,1.000000,0.847621,-0.072213,-0.004852,0.106389,-0.027540,0.326688
AveBedrms,-0.062040,-0.077747,0.847621,1.000000,-0.066197,-0.006181,0.069721,0.013344,-0.066910
Population,0.004834,-0.296244,-0.072213,-0.066197,1.000000,0.069863,-0.108785,0.099773,0.018415
AveOccup,0.018766,0.013191,-0.004852,-0.006181,0.069863,1.000000,0.002366,0.002476,0.015266
Latitude,-0.079809,0.011173,0.106389,0.069721,-0.108785,0.002366,1.000000,-0.924664,-0.084303
Longitude,-0.015176,-0.108197,-0.027540,0.013344,0.099773,0.002476,-0.924664,1.000000,-0.015569
MedInc_Sqrt,0.984329,-0.132797,0.326688,-0.066910,0.018415,0.015266,-0.084303,-0.015569,1.000000

In [9]:
var_thresh = VarianceThreshold(threshold=0.3)

In [10]:
transformed_data = var_thresh.fit_transform(df)

In [11]:
var_thresh.get_support()

array([ True,  True,  True, False,  True,  True,  True,  True, False])

In [12]:
transformed_data.shape

(20640, 7)

In [13]:
df.shape

(20640, 9)

In [14]:
df[df.columns[var_thresh.get_support()]]

       MedInc  HouseAge  AveRooms  Population  AveOccup  Latitude  Longitude
0      8.3252      41.0  6.984127       322.0  2.555556     37.88    -122.23
1      8.3014      21.0  6.238137      2401.0  2.109842     37.86    -122.22
2      7.2574      52.0  8.288136       496.0  2.802260     37.85    -122.24
3      5.6431      52.0  5.817352       558.0  2.547945     37.85    -122.25
4      3.8462      52.0  6.281853       565.0  2.181467     37.85    -122.25
...       ...       ...       ...         ...       ...       ...        ...
20635  1.5603      25.0  5.045455       845.0  2.560606     39.48    -121.09
20636  2.5568      18.0  6.114035       356.0  3.122807     39.49    -121.21
20637  1.7000      17.0  5.205543      1007.0  2.325635     39.43    -121.22
20638  1.8672      18.0  5.329513       741.0  2.123209     39.43    -121.32
20639  2.3886      16.0  5.254717      1387.0  2.616981     39.37    -121.24

[20640 rows x 7 columns]

In [15]:
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedInc_Sqrt
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,2.885342
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,2.881215
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,2.693956
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,2.375521
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,1.961173
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,1.249120
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,1.599000
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,1.303840
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,1.366455
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,1.545510